import aragulaRocket from "../../public/assets/images/produk/aragula-rocket.jpg";
import brokoli from "../../public/assets/images/produk/brokoli.jpg";
import basil from "../../public/assets/images/produk/basil.jpg";
import daunKetumbar from "../../public/assets/images/produk/daun-ketumbar.jpg";
import kolUngu from "../../public/assets/images/produk/kol-ungu.jpg";
import lolorosa from "../../public/assets/images/produk/lolorosa.jpg";
import lettuce from "../../public/assets/images/produk/lettuce.jpg";
import parsley from "../../public/assets/images/produk/parsley.jpg";
import radisio from "../../public/assets/images/produk/radisio.jpg";
import romaine from "../../public/assets/images/produk/romaine.jpg";
import thyme from "../../public/assets/images/produk/thyme.jpg";
import tomatCherryKuning from "../../public/assets/images/produk/tomat-cherry.jpg";
import babyBuncis from "../../public/assets/images/produk/baby-buncis-kenya.jpg";
import selada from "../../public/assets/images/produk/selada.jpg";
import ceriKuning from "../../public/assets/images/produk/ceri-kuning.jpg";
import asparagus from "../../public/assets/images/produk/asparagus.jpg";
import horenzo from "../../public/assets/images/produk/horenzo.jpg";
import comeo from "../../public/assets/images/produk/comeo.jpg";
import sawiPagoda from "../../public/assets/images/produk/sawi-pagoda.jpg";
import seledriLokal from "../../public/assets/images/produk/seledri.jpg";
import sawiPutih from "../../public/assets/images/produk/sawi-putih.jpg";
import redRadish from "../../public/assets/images/produk/red-radish.jpg";
import kembangKol from "../../public/assets/images/produk/kembang-kol.jpg";
import tomatBeef from "../../public/assets/images/produk/tomat-beef.jpg";
import babyCorn from "../../public/assets/images/produk/baby-corn.jpg";
import lobak from "../../public/assets/images/produk/lobak.jpg";
import buncisSuper from "../../public/assets/images/produk/buncis-super.jpg";
import babyKailan from "../../public/assets/images/produk/baby-kailan.jpg";
import lemonCalifornia from "../../public/assets/images/produk/lemon-california.jpg";
import daunBawang from "../../public/assets/images/produk/daun-bawang-chung.jpg";
import pakcoyKonvensional from "../../public/assets/images/produk/pakcoy-konvensional.jpg";
import pakcoyHidroponik from "../../public/assets/images/produk/pakcoy-hidroponik.jpg";
import type { TProduct, TProductCategory } from "@/types/typesDefinitions";

export const productData: TProduct[] = [
  {
    image: aragulaRocket,
    name: "Aragula Rocket",
    alt: "menyediakan Aragula Rocket",
  },
  {
    image: horenzo,
    name: "Horenzo",
    alt: "menyediakan Horenzo",
  },
  {
    image: daunKetumbar,
    name: "Daun Ketumbar",
    alt: "menyediakan Daun Ketumbar",
  },
  {
    image: kolUngu,
    name: "Kol Ungu",
    alt: "menyediakan Kol Ungu",
  },
  {
    image: lettuce,
    name: "Lettuce",
    alt: "menyediakan Lettuce",
  },
  {
    image: lolorosa,
    name: "Lolorosa",
    alt: "menyediakan Lolorosa",
  },
  {
    image: parsley,
    name: "Parsley",
    alt: "menyediakan Parsley",
  },
  {
    image: radisio,
    name: "Radisio",
    alt: "menyediakan Radisio",
  },
  {
    image: romaine,
    name: "Romaine",
    alt: "menyediakan Romaine",
  },
  {
    image: thyme,
    name: "Thyme",
    alt: "menyediakan Thyme",
  },
  {
    image: tomatCherryKuning,
    name: "Tomat Cherry",
    alt: "menyediakan Tomat Cherry",
  },
  {
    image: babyBuncis,
    name: "Baby Buncis Kenya",
    alt: "menyediakan Baby Buncis Kenya",
  },
  {
    image: selada,
    name: "Selada",
    alt: "menyediakan Selada",
  },
  {
    image: ceriKuning,
    name: "Ceri Kuning",
    alt: "menyediakan Ceri Kuning",
  },
  {
    image: asparagus,
    name: "Asparagus",
    alt: "menyediakan Asparagus",
  },
  {
    image: comeo,
    name: "Comeo",
    alt: "menyediakan Comeo",
  },
  {
    image: sawiPagoda,
    name: "Sawi Pagoda",
    alt: "menyediakan Sawi Pagoda",
  },
  {
    image: seledriLokal,
    name: "Seledri Stik Lokal",
    alt: "menyediakan Seledri Stik Lokal",
  },
  {
    image: sawiPutih,
    name: "Sawi Putih",
    alt: "menyediakan Sawi Putih",
  },
  {
    image: redRadish,
    name: "Red Radish",
    alt: "menyediakan Red Radish",
  },
  {
    image: kembangKol,
    name: "Kembang Kol",
    alt: "menyediakan Kembang Kol",
  },
  {
    image: tomatBeef,
    name: "Tomat Beef",
    alt: "menyediakan Tomat Beef",
  },
  {
    image: babyCorn,
    name: "Baby Corn",
    alt: "menyediakan Baby Corn",
  },
  {
    image: lobak,
    name: "Lobak",
    alt: "menyediakan Lobak",
  },
  {
    image: buncisSuper,
    name: "Buncis Super",
    alt: "menyediakan Buncis Super",
  },
  {
    image: babyKailan,
    name: "Baby Kailan",
    alt: "menyediakan Baby Kailan",
  },
  {
    image: lemonCalifornia,
    name: "Lemon California Premium",
    alt: "menyediakan Lemon California Premium",
  },
  {
    image: daunBawang,
    name: "Daun Bawang Chung",
    alt: "menyediakan Daun Bawang Chung",
  },
  {
    image: pakcoyKonvensional,
    name: "Pakcoy Konvensional",
    alt: "menyediakan Pakcoy Konvensional",
  },
  {
    image: pakcoyHidroponik,
    name: "Pakcoy Hidroponik",
    alt: "menyediakan Pakcoy Hidroponik",
  },
  {
    image: brokoli,
    name: "Brokoli",
    alt: "menyediakan Brokoli",
  },
  {
    image: basil,
    name: "Basil",
    alt: "menyediakan Basil",
  },
];

export const uniqueVegetablesData: TProductCategory[] = [
  {
    id: 1,
    name: "Baby Buncis",
    unit: "kg",
    price: 40000,
  },
  {
    id: 2,
    name: "Brokoli bersih 4 jari",
    unit: "kg",
    price: 46000,
  },
  {
    id: 3,
    name: "Brokoli Import",
    unit: "kg",
    price: 55000,
  },
  {
    id: 4,
    name: "Daun Basil Fresh",
    unit: "kg",
    price: 65000,
  },
  {
    id: 5,
    name: "Daun Ketumbar",
    unit: "kg",
    price: 80000,
  },
  {
    id: 6,
    name: "Daun Thyme",
    unit: "pack",
    price: 12000,
  },
  {
    id: 7,
    name: "Kol Ungu",
    unit: "kg",
    price: 45000,
  },
  {
    id: 8,
    name: "Lettuce Head",
    unit: "kg",
    price: 26000,
  },
  {
    id: 9,
    name: "Lolorosa",
    unit: "kg",
    price: 65000,
  },
  {
    id: 10,
    name: "Paprika Hijau",
    unit: "kg",
    price: 70000,
  },
  {
    id: 11,
    name: "Paprika Kuning",
    unit: "kg",
    price: 130000,
  },
  {
    id: 12,
    name: "Paprika Merah",
    unit: "kg",
    price: 120000,
  },
  {
    id: 13,
    name: "Parsley",
    unit: "kg",
    price: 35000,
  },
  {
    id: 14,
    name: "Radisio",
    unit: "kg",
    price: 60000,
  },
  {
    id: 15,
    name: "Romaine",
    unit: "kg",
    price: 25000,
  },
  {
    id: 16,
    name: "Rosemary Leaf",
    unit: "pack",
    price: 10000,
  },
  {
    id: 17,
    name: "Selada Keriting",
    unit: "kg",
    price: 22000,
  },
  {
    id: 18,
    name: "Timun Jepang",
    unit: "kg",
    price: 22000,
  },
  {
    id: 19,
    name: "Tomat Ceri",
    unit: "kg",
    price: 32000,
  },
  {
    id: 20,
    name: "Zukini",
    unit: "kg",
    price: 28000,
  },
];

export const vegetablesData: TProductCategory[] = [
  {
    id: 1,
    name: "Asam Jawa",
    unit: "kg",
    price: 60000,
  },
  {
    id: 2,
    name: "Asam Kandis",
    unit: "kg",
    price: 36000,
  },
  {
    id: 3,
    name: "Basil Kering",
    unit: "btl",
    price: 25000,
  },
  {
    id: 4,
    name: "Basil Kering 250gr",
    unit: "kg",
    price: 50000,
  },
  {
    id: 5,
    name: "Bawang Bombay",
    unit: "kg",
    price: 27000,
  },
  {
    id: 6,
    name: "Bawang Bombay - krg",
    unit: "kg",
    price: 480000,
  },
  {
    id: 7,
    name: "Bawang Merah",
    unit: "kg",
    price: 38000,
  },
  {
    id: 8,
    name: "Bawang Merah Kupas",
    unit: "kg",
    price: 46000,
  },
  {
    id: 9,
    name: "Bawang Putih",
    unit: "kg",
    price: 44000,
  },
  {
    id: 10,
    name: "Bawang Putih Kating",
    unit: "kg",
    price: 48000,
  },
  {
    id: 11,
    name: "Bawang Putih Kupas",
    unit: "kg",
    price: 550000,
  },
  {
    id: 12,
    name: "Bayam",
    unit: "ikat",
    price: 3000,
  },
  {
    id: 13,
    name: "Bengkoang",
    unit: "kg",
    price: 13000,
  },
  {
    id: 14,
    name: "Biji Jinten",
    unit: "kg",
    price: 280000,
  },
  {
    id: 15,
    name: "Bit",
    unit: "kg",
    price: 28000,
  },
  {
    id: 16,
    name: "Buncis Biasa",
    unit: "kg",
    price: 23000,
  },
  {
    id: 17,
    name: "Bunga Lawang",
    unit: "kg",
    price: 210000,
  },
  {
    id: 18,
    name: "Cabe Ijo Gede (TW)",
    unit: "kg",
    price: 40000,
  },
  {
    id: 19,
    name: "Cabe Jalapeno (cabe gendot)",
    unit: "kg",
    price: 60000,
  },
  {
    id: 20,
    name: "Cabe Kering",
    unit: "kg",
    price: 90000,
  },
  {
    id: 21,
    name: "Cabe Keriting Hijau",
    unit: "kg",
    price: 55000,
  },
  {
    id: 22,
    name: "Cabe Keriting Merah",
    unit: "kg",
    price: 90000,
  },
  {
    id: 23,
    name: "Cabe Merah Besar",
    unit: "kg",
    price: 80000,
  },
  {
    id: 24,
    name: "Cabe Merah Keriting",
    unit: "kg",
    price: 40000,
  },
  {
    id: 25,
    name: "Cabe Rawit Ijo",
    unit: "kg",
    price: 85000,
  },
  {
    id: 26,
    name: "Cabe Rawit Merah Ekonomis",
    unit: "kg",
    price: 90000,
  },
  {
    id: 27,
    name: "Cabe Rawit Merah Ori",
    unit: "kg",
    price: 100000,
  },
  {
    id: 28,
    name: "Cengkeh",
    unit: "kg",
    price: 200000,
  },
  {
    id: 29,
    name: "Daun Bawang",
    unit: "kg",
    price: 22000,
  },
  {
    id: 30,
    name: "Daun Jeruk",
    unit: "kg",
    price: 55000,
  },
  {
    id: 31,
    name: "Daun Kari",
    unit: "kg",
    price: 10000,
  },
  {
    id: 32,
    name: "Daun Pandan",
    unit: "kg",
    price: 6000,
  },
  {
    id: 33,
    name: "Daun Salam",
    unit: "kg",
    price: 40000,
  },
  {
    id: 34,
    name: "Daun Seledri",
    unit: "kg",
    price: 38000,
  },
  {
    id: 35,
    name: "Ebi Kering",
    unit: "kg",
    price: 100000,
  },
  {
    id: 36,
    name: "Jagung Kulit",
    unit: "kg",
    price: 12000,
  },
  {
    id: 37,
    name: "Jagung Manis",
    unit: "kg",
    price: 15000,
  },
  {
    id: 38,
    name: "Jagung Putren Kupas",
    unit: "kg",
    price: 33000,
  },
  {
    id: 39,
    name: "Jahe",
    unit: "kg",
    price: 33000,
  },
  {
    id: 40,
    name: "Jamur Champignon",
    unit: "kg",
    price: 45000,
  },
  {
    id: 41,
    name: "Jamur Kuping",
    unit: "kg",
    price: 32000,
  },
  {
    id: 42,
    name: "Jamur Kuping Kering",
    unit: "kg",
    price: 100000,
  },
  {
    id: 43,
    name: "Jamur Merang",
    unit: "kg",
    price: 60000,
  },
  {
    id: 44,
    name: "Jamur Shimeji Putih",
    unit: "pack",
    price: 15000,
  },
  {
    id: 45,
    name: "Jeruk Limo",
    unit: "kg",
    price: 45000,
  },
  {
    id: 46,
    name: "Jeruk Nipis",
    unit: "kg",
    price: 18000,
  },
  {
    id: 47,
    name: "Kacang Giling",
    unit: "kg",
    price: 35000,
  },
  {
    id: 48,
    name: "Kacang Merah",
    unit: "kg",
    price: 36000,
  },
  {
    id: 49,
    name: "Kacang Panjang",
    unit: "kg",
    price: 16000,
  },
  {
    id: 50,
    name: "Kangkung",
    unit: "kg",
    price: 15000,
  },
  {
    id: 51,
    name: "Kangkung - iket",
    unit: "ikat",
    price: 3000,
  },
  {
    id: 52,
    name: "Kapulaga",
    unit: "kg",
    price: 200000,
  },
  {
    id: 53,
    name: "Kayu Manis",
    unit: "kg",
    price: 130000,
  },
  {
    id: 54,
    name: "Kayu Manis Bubuk",
    unit: "kg",
    price: 150000,
  },
  {
    id: 55,
    name: "Kecambah",
    unit: "kg",
    price: 24000,
  },
  {
    id: 56,
    name: "Kemangi",
    unit: "kg",
    price: 40000,
  },
  {
    id: 57,
    name: "Kembang Kol",
    unit: "kg",
    price: 25000,
  },
  {
    id: 58,
    name: "Kemiri",
    unit: "kg",
    price: 76000,
  },
  {
    id: 59,
    name: "Kemiri Belah",
    unit: "kg",
    price: 80000,
  },
  {
    id: 60,
    name: "Kencur",
    unit: "kg",
    price: 34000,
  },
  {
    id: 61,
    name: "Kentang Besar",
    unit: "kg",
    price: 25000,
  },
  {
    id: 62,
    name: "Kentang Dieng",
    unit: "kg",
    price: 20000,
  },
  {
    id: 63,
    name: "Kentang Sedang",
    unit: "kg",
    price: 18000,
  },
  {
    id: 64,
    name: "Ketumbar",
    unit: "kg",
    price: 54000,
  },
  {
    id: 65,
    name: "Kluwek",
    unit: "kg",
    price: 30000,
  },
  {
    id: 66,
    name: "Kol",
    unit: "kg",
    price: 12000,
  },
  {
    id: 67,
    name: "Kol Putih",
    unit: "kg",
    price: 12000,
  },
  {
    id: 68,
    name: "Kucay",
    unit: "iket",
    price: 2000,
  },
  {
    id: 69,
    name: "Kunyit",
    unit: "kg",
    price: 17000,
  },
  {
    id: 70,
    name: "Kunyit Bubuk",
    unit: "kg",
    price: 288000,
  },
  {
    id: 71,
    name: "Labu Parang",
    unit: "kg",
    price: 15000,
  },
  {
    id: 72,
    name: "Lada Bulat",
    unit: "kg",
    price: 160000,
  },
  {
    id: 73,
    name: "Lada Putih Biji",
    unit: "kg",
    price: 180000,
  },
  {
    id: 74,
    name: "Lengkoas",
    unit: "kg",
    price: 15000,
  },
  {
    id: 75,
    name: "Lobak",
    unit: "kg",
    price: 16000,
  },
  {
    id: 76,
    name: "Lobak Merah",
    unit: "kg",
    price: 35000,
  },
  {
    id: 77,
    name: "Pala Bulat",
    unit: "kg",
    price: 200000,
  },
  {
    id: 78,
    name: "Parsley Kering",
    unit: "kg",
    price: 32000,
  },
  {
    id: 79,
    name: "Rosemary Kering Jay's",
    unit: "btl",
    price: 30000,
  },
  {
    id: 80,
    name: "Sawi Asin",
    unit: "kg",
    price: 32000,
  },
  {
    id: 81,
    name: "Sawi Hijau",
    unit: "kg",
    price: 12000,
  },
  {
    id: 82,
    name: "Sawi Ijo",
    unit: "kg",
    price: 12000,
  },
  {
    id: 83,
    name: "Sawi Putih",
    unit: "kg",
    price: 24000,
  },
  {
    id: 84,
    name: "Sedap Malam",
    unit: "kg",
    price: 150000,
  },
  {
    id: 85,
    name: "Seledri",
    unit: "kg",
    price: 38000,
  },
  {
    id: 86,
    name: "Sereh",
    unit: "kg",
    price: 15000,
  },
  {
    id: 87,
    name: "Sereh, Daun Jeruk",
    unit: "200gr",
    price: 7000,
  },
  {
    id: 88,
    name: "Singkong",
    unit: "kg",
    price: 8000,
  },
  {
    id: 89,
    name: "Tauge",
    unit: "kg",
    price: 12000,
  },
  {
    id: 90,
    name: "Tauge Panjang",
    unit: "kg",
    price: 14000,
  },
  {
    id: 91,
    name: "Timun",
    unit: "kg",
    price: 15000,
  },
  {
    id: 92,
    name: "Timun Lokal",
    unit: "kg",
    price: 16000,
  },
  {
    id: 93,
    name: "Toge",
    unit: "kg",
    price: 12000,
  },
  {
    id: 94,
    name: "Tomat Ekonomis",
    unit: "kg",
    price: 16000,
  },
  {
    id: 95,
    name: "Tomat Hijau",
    unit: "kg",
    price: 14000,
  },
  {
    id: 96,
    name: "Tomat Merah Premium",
    unit: "kg",
    price: 20000,
  },
  {
    id: 97,
    name: "Cabe Merah Besar",
    unit: "kg",
    price: 75000,
  },
  {
    id: 98,
    name: "Wortel Import",
    unit: "kg",
    price: 17000,
  },
  {
    id: 99,
    name: "Wortel Lokal",
    unit: "kg",
    price: 13000,
  },
];

export const fruitData: TProductCategory[] = [
  {
    id: 1,
    name: "Air Kelapa Ijo",
    unit: "buah",
    price: 16000,
  },
  {
    id: 2,
    name: "Alpukat",
    unit: "buah",
    price: 36000,
  },
  {
    id: 3,
    name: "Apel Fuji",
    unit: "kg",
    price: 40000,
  },
  {
    id: 4,
    name: "Buah Anggur",
    unit: "kg",
    price: 88000,
  },
  {
    id: 5,
    name: "Buah Ceri",
    unit: "200gr",
    price: 15000,
  },
  {
    id: 6,
    name: "Buah Kiwie",
    unit: "box",
    price: 36000,
  },
  {
    id: 7,
    name: "Buah Naga",
    unit: "kg",
    price: 27000,
  },
  {
    id: 8,
    name: "Buah Strawberry",
    unit: "pack",
    price: 15000,
  },
  {
    id: 9,
    name: "Jambu Air",
    unit: "kg",
    price: 20000,
  },
  {
    id: 10,
    name: "Jambu Biji",
    unit: "kg",
    price: 28000,
  },
  {
    id: 11,
    name: "Jeruk Lemon California",
    unit: "kg",
    price: 28000,
  },
  {
    id: 12,
    name: "Jeruk Santang",
    unit: "kg",
    price: 40000,
  },
  {
    id: 13,
    name: "Jeruk Malang",
    unit: "kg",
    price: 20000,
  },
  {
    id: 14,
    name: "Jeruk Medan",
    unit: "kg",
    price: 26000,
  },
  {
    id: 15,
    name: "Jeruk Peras",
    unit: "kg",
    price: 18000,
  },
  {
    id: 16,
    name: "Jeruk Pontianak",
    unit: "kg",
    price: 20000,
  },
  {
    id: 17,
    name: "Jeruk Santang Medan",
    unit: "kg",
    price: 40000,
  },
  {
    id: 18,
    name: "Jeruk Sunkist",
    unit: "kg",
    price: 38000,
  },
  {
    id: 19,
    name: "Kelapa Muda",
    unit: "buah",
    price: 18000,
  },
  {
    id: 20,
    name: "Lemon Impor",
    unit: "kg",
    price: 23000,
  },
  {
    id: 21,
    name: "Lemon Kuning Fresh",
    unit: "kg",
    price: 17000,
  },
  {
    id: 22,
    name: "Lemon Lokal",
    unit: "kg",
    price: 18000,
  },
  {
    id: 23,
    name: "Mangga Harum Manis",
    unit: "kg",
    price: 23000,
  },
  {
    id: 24,
    name: "Mangga Muda",
    unit: "kg",
    price: 20000,
  },
  {
    id: 25,
    name: "Melon",
    unit: "kg",
    price: 22000,
  },
  {
    id: 26,
    name: "Nanas Honi",
    unit: "buah",
    price: 30000,
  },
  {
    id: 27,
    name: "Nanas Madu",
    unit: "buah",
    price: 6000,
  },
  {
    id: 28,
    name: "Nanas Madu Palembang",
    unit: "buah",
    price: 10000,
  },
  {
    id: 29,
    name: "Nanas Madu Palembang Kecil",
    unit: "buah",
    price: 8000,
  },
  {
    id: 30,
    name: "Nanas Palembang",
    unit: "buah",
    price: 10000,
  },
  {
    id: 31,
    name: "Nanas Sunpride",
    unit: "buah",
    price: 30000,
  },
  {
    id: 32,
    name: "Pepaya",
    unit: "kg",
    price: 14000,
  },
  {
    id: 33,
    name: "Pisang Ambon",
    unit: "sisir",
    price: 20000,
  },
  {
    id: 34,
    name: "Pisang Barangan",
    unit: "sisir",
    price: 25000,
  },
  {
    id: 35,
    name: "Pisang Cavendish",
    unit: "pcs",
    price: 5000,
  },
  {
    id: 36,
    name: "Pisang Cavendish - sisir",
    unit: "sisir",
    price: 30000,
  },
  {
    id: 37,
    name: "Pisang Kepok Gede",
    unit: "sisir",
    price: 33000,
  },
  {
    id: 38,
    name: "Pisang Sunpride",
    unit: "buah",
    price: 5000,
  },
  {
    id: 39,
    name: "Salak Podoh",
    unit: "kg",
    price: 14000,
  },
  {
    id: 40,
    name: "Semangka",
    unit: "kg",
    price: 13000,
  },
];

export const meatData: TProductCategory[] = [
  {
    id: 1,
    name: "Cumi Asin",
    unit: "kg",
    price: 100000,
  },
  {
    id: 2,
    name: "Cumi Segar",
    unit: "kg",
    price: 90000,
  },
  {
    id: 3,
    name: "Daging Has Dalam Fresh",
    unit: "kg",
    price: 132000,
  },
  {
    id: 4,
    name: "Daging Lontong",
    unit: "kg",
    price: 100000,
  },
  {
    id: 5,
    name: "Ikan Cakalang Asap",
    unit: "kg",
    price: 80000,
  },
  {
    id: 6,
    name: "Ikan Cucut",
    unit: "kg",
    price: 38000,
  },
  {
    id: 7,
    name: "Ikan Dori Fillet",
    unit: "kg",
    price: 38000,
  },
  {
    id: 8,
    name: "Ikan Kembung",
    unit: "kg",
    price: 45000,
  },
  {
    id: 9,
    name: "Ikan Mas",
    unit: "kg",
    price: 36000,
  },
  {
    id: 10,
    name: "Ikan Salem",
    unit: "kg",
    price: 28000,
  },
  {
    id: 11,
    name: "Ikan Tenggiri Fillet",
    unit: "kg",
    price: 105000,
  },
  {
    id: 12,
    name: "Ikan Tongkol Fresh",
    unit: "kg",
    price: 50000,
  },
  {
    id: 13,
    name: "Kulit Kikil",
    unit: "kg",
    price: 25000,
  },
  {
    id: 14,
    name: "Saikoro (500gr)",
    unit: "pack",
    price: 70000,
  },
  {
    id: 15,
    name: "Salmon Fillet/pack",
    unit: "pack",
    price: 38000,
  },
  {
    id: 16,
    name: "Sirloin Meltique 200gr",
    unit: "kg",
    price: 37000,
  },
  {
    id: 17,
    name: "Slice Beef Teriyaki 500gr",
    unit: "kg",
    price: 65000,
  },
  {
    id: 18,
    name: "Slice Beef Yoshinoya (Ekonomis) 500gr",
    unit: "kg",
    price: 60000,
  },
  {
    id: 19,
    name: "Slice Beef Yoshinoya (Premium) 250gr",
    unit: "kg",
    price: 38000,
  },
  {
    id: 20,
    name: "Slice Beef Yoshinoya (Premium) 500gr",
    unit: "kg",
    price: 75000,
  },
  {
    id: 21,
    name: "Tenderloin Meltique 200gr",
    unit: "kg",
    price: 37000,
  },
  {
    id: 22,
    name: "Tulang Sapi",
    unit: "kg",
    price: 45000,
  },
  {
    id: 23,
    name: "Udang Vaname Kecil",
    unit: "kg",
    price: 60000,
  },
];

export const chickenData: TProductCategory[] = [
  {
    id: 1,
    name: "Ati Ampela",
    unit: "pcs",
    price: 2800,
  },
  {
    id: 2,
    name: "Ayam Karkas 1.1 - 1.4",
    unit: "ekor",
    price: 33000,
  },
  {
    id: 3,
    name: "Ayam Karkas Besar",
    unit: "ekor",
    price: 32500,
  },
  {
    id: 4,
    name: "Ayam Utuh",
    unit: "ekor",
    price: 28000,
  },
  {
    id: 5,
    name: "Ceker Ayam Tanpa Kuku",
    unit: "kg",
    price: 26000,
  },
  {
    id: 6,
    name: "Dada Fillet",
    unit: "kg",
    price: 45000,
  },
  {
    id: 7,
    name: "Dada Fillet Kulit",
    unit: "kg",
    price: 43000,
  },
  {
    id: 8,
    name: "Kepala",
    unit: "kg",
    price: 12000,
  },
  {
    id: 9,
    name: "Kerongkongan",
    unit: "kg",
    price: 15000,
  },
  {
    id: 10,
    name: "Kulit (Paha, Dada)",
    unit: "kg",
    price: 30000,
  },
  {
    id: 11,
    name: "Paha Fillet",
    unit: "kg",
    price: 44000,
  },
  {
    id: 12,
    name: "Paha Pentung",
    unit: "kg",
    price: 40000,
  },
  {
    id: 13,
    name: "Paha Utuh",
    unit: "kg",
    price: 41000,
  },
  {
    id: 14,
    name: "Sayap",
    unit: "kg",
    price: 33000,
  },
];

export const frozenFoodData: TProductCategory[] = [
  {
    id: 1,
    name: "Bakso Ayam Champ 500gr",
    unit: "pack",
    price: 30000,
  },
  {
    id: 2,
    name: "Bakso Sapi Besar Premium (isi 50)",
    unit: "pack",
    price: 50000,
  },
  {
    id: 3,
    name: "Bakso Sapi Daun Jeruk",
    unit: "pack",
    price: 45000,
  },
  {
    id: 4,
    name: "Bakso Sapi Isi 50",
    unit: "pack",
    price: 22000,
  },
  {
    id: 5,
    name: "Bakso Sapi Warisan Isi 50pcs",
    unit: "pack",
    price: 32000,
  },
  {
    id: 6,
    name: "Bakso Sumber Selera Isi 10",
    unit: "pack",
    price: 6000,
  },
  {
    id: 7,
    name: "Bakso Sumber Selera Isi 20",
    unit: "pack",
    price: 8000,
  },
  {
    id: 8,
    name: "Beef Burger Yona 500gr",
    unit: "kg",
    price: 45000,
  },
  {
    id: 9,
    name: "Cedea Bola Salmon 200gr (isi 12pcs)",
    unit: "pack",
    price: 17000,
  },
  {
    id: 10,
    name: "Cedea Chikuwa 250gr",
    unit: "pack",
    price: 20000,
  },
  {
    id: 11,
    name: "Cedea Dumpling Keju 200gr (isi 12pcs)",
    unit: "pack",
    price: 18000,
  },
  {
    id: 12,
    name: "Cedea Dumpling Keju 500gr",
    unit: "pack",
    price: 32000,
  },
  {
    id: 13,
    name: "Cedea Korean Odeng Original 480gr",
    unit: "pack",
    price: 32000,
  },
  {
    id: 14,
    name: "Daging Burger Hemato (isi 10pcs)",
    unit: "pack",
    price: 12000,
  },
  {
    id: 15,
    name: "Kentang Goreng Aviko Straight Cut 2,5 kg",
    unit: "pack",
    price: 77000,
  },
  {
    id: 16,
    name: "Nugget Champ 225gr",
    unit: "pack",
    price: 22000,
  },
  {
    id: 17,
    name: "Nugget Hemato 500gr",
    unit: "pack",
    price: 13000,
  },
  {
    id: 18,
    name: "Otak-otak Athien isi 10",
    unit: "pack",
    price: 10000,
  },
  {
    id: 19,
    name: "Smoked Beef Yona 500gr",
    unit: "kg",
    price: 60000,
  },
  {
    id: 20,
    name: "Sosis Ayam Champ isi 15",
    unit: "pack",
    price: 20000,
  },
  {
    id: 21,
    name: "Sosis Geboy Merah",
    unit: "pack",
    price: 16000,
  },
  {
    id: 22,
    name: "Sosis Geboy Putih",
    unit: "pack",
    price: 16000,
  },
  {
    id: 23,
    name: "Sosis Kichick 500gr",
    unit: "pack",
    price: 33000,
  },
  {
    id: 24,
    name: "Sosis Sapi Yona Isi 3",
    unit: "pack",
    price: 7000,
  },
  {
    id: 25,
    name: "Sosis Zaitun Sapi 500gr",
    unit: "pack",
    price: 40000,
  },
];

export const groceriesData: TProductCategory[] = [
  {
    id: 1,
    name: "Air Soda",
    unit: "btl",
    price: 8000,
  },
  {
    id: 2,
    name: "Almond Bubuk",
    unit: "kg",
    price: 240000,
  },
  {
    id: 3,
    name: "Almond Slice",
    unit: "bks",
    price: 24000,
  },
  {
    id: 4,
    name: "Alumunium Foil",
    unit: "roll",
    price: 18000,
  },
  {
    id: 5,
    name: "Astor",
    unit: "pack",
    price: 22000,
  },
  {
    id: 6,
    name: "Astor - kcl",
    unit: "pack",
    price: 10000,
  },
  {
    id: 7,
    name: "Baked Beans",
    unit: "kaleng",
    price: 25000,
  },
  {
    id: 8,
    name: "Baking Paper",
    unit: "roll",
    price: 34000,
  },
  {
    id: 9,
    name: "Baking Powder",
    unit: "pcs",
    price: 10000,
  },
  {
    id: 10,
    name: "Baking Powder Kupu-Kupu",
    unit: "btl",
    price: 12000,
  },
  {
    id: 11,
    name: "Baking Soda",
    unit: "klg",
    price: 8000,
  },
  {
    id: 12,
    name: "Baking Soda Kupu-Kupu",
    unit: "btl",
    price: 12000,
  },
  {
    id: 13,
    name: "Bawang Goreng",
    unit: "kg",
    price: 120000,
  },
  {
    id: 14,
    name: "Bawang Goreng - bks",
    unit: "bks",
    price: 16000,
  },
  {
    id: 15,
    name: "Bawang Merah Goreng",
    unit: "kg",
    price: 115000,
  },
  {
    id: 16,
    name: "Bawang Putih Goreng",
    unit: "kg",
    price: 160000,
  },
  {
    id: 17,
    name: "Beras Ketan",
    unit: "kg",
    price: 20000,
  },
  {
    id: 18,
    name: "Beras Merah",
    unit: "kg",
    price: 22000,
  },
  {
    id: 19,
    name: "Bihun AA",
    unit: "pack",
    price: 25000,
  },
  {
    id: 20,
    name: "Bihun Jagung",
    unit: "bks",
    price: 10000,
  },
  {
    id: 21,
    name: "Bihun Naga",
    unit: "kg",
    price: 48000,
  },
  {
    id: 22,
    name: "Bihun Naga 250gr",
    unit: "pack",
    price: 12000,
  },
  {
    id: 23,
    name: "Bihun Tanam Jagung",
    unit: "pack",
    price: 12000,
  },
  {
    id: 24,
    name: "Biji Wijen",
    unit: "kg",
    price: 80000,
  },
  {
    id: 25,
    name: "Black Pepper Crushed 50gr",
    unit: "btl",
    price: 42000,
  },
  {
    id: 26,
    name: "Black Pepper Curah",
    unit: "kg",
    price: 150000,
  },
  {
    id: 27,
    name: "Blueband",
    unit: "kg",
    price: 38000,
  },
  {
    id: 28,
    name: "Blueband - dus",
    unit: "kg",
    price: 510000,
  },
  {
    id: 29,
    name: "Bread Improver",
    unit: "kg",
    price: 200000,
  },
  {
    id: 30,
    name: "Brown Bread",
    unit: "pack",
    price: 25000,
  },
  {
    id: 31,
    name: "Buavita Orange",
    unit: "btl",
    price: 13000,
  },
  {
    id: 32,
    name: "Buavita Orange 1L",
    unit: "liter",
    price: 45000,
  },
  {
    id: 33,
    name: "Bubuk Bordeaux Tulip 100gr",
    unit: "bks",
    price: 30000,
  },
  {
    id: 34,
    name: "Bubuk Bordeaux Tulip 250gr",
    unit: "bks",
    price: 280000,
  },
  {
    id: 35,
    name: "Bumbu Gado-Gado Sinti",
    unit: "pack",
    price: 7000,
  },
  {
    id: 36,
    name: "Bumbu Pecel Sinti",
    unit: "pcs",
    price: 7000,
  },
  {
    id: 37,
    name: "Bumbu Ungkeb Ayam",
    unit: "bks",
    price: 5000,
  },
  {
    id: 38,
    name: "Butter Orchid",
    unit: "kg",
    price: 150000,
  },
  {
    id: 39,
    name: "Cabai Bubuk Powder (Aida)",
    unit: "pack",
    price: 5000,
  },
  {
    id: 40,
    name: "Cepers Pikle",
    unit: "btl",
    price: 93000,
  },
  {
    id: 41,
    name: "Cling Merk Indomaret",
    unit: "pcs",
    price: 8000,
  },
  {
    id: 42,
    name: "Coca Cola",
    unit: "lt",
    price: 15000,
  },
  {
    id: 43,
    name: "Coca Cola Mix Original",
    unit: "btl",
    price: 10000,
  },
  {
    id: 44,
    name: "Coca Cola Zero Sugar",
    unit: "btl",
    price: 10000,
  },
  {
    id: 45,
    name: "Collata Choco Chips 150gr",
    unit: "bks",
    price: 20000,
  },
  {
    id: 46,
    name: "Collata Dark 250gr",
    unit: "pcs",
    price: 30000,
  },
  {
    id: 47,
    name: "Collata White 250gr",
    unit: "pcs",
    price: 30000,
  },
  {
    id: 48,
    name: "Condy Lemon 500ml",
    unit: "btl",
    price: 58500,
  },
  {
    id: 49,
    name: "Craft Chedar",
    unit: "kg",
    price: 105000,
  },
  {
    id: 50,
    name: "Craft Chedar Slice",
    unit: "pack",
    price: 17000,
  },
  {
    id: 51,
    name: "Cream Cheese",
    unit: "pack",
    price: 65000,
  },
  {
    id: 52,
    name: "Cream of Tartar",
    unit: "btl",
    price: 12000,
  },
  {
    id: 53,
    name: "Cuka Apel Cedar",
    unit: "btl",
    price: 85000,
  },
  {
    id: 54,
    name: "Cuka Dixi",
    unit: "btl",
    price: 20000,
  },
  {
    id: 55,
    name: "Cuka Dixi - Kecil",
    unit: "btl",
    price: 7000,
  },
  {
    id: 56,
    name: "Cup Cake Case",
    unit: "pack",
    price: 35000,
  },
  {
    id: 57,
    name: "Cup Cake Casee Polos",
    unit: "pack",
    price: 27000,
  },
  {
    id: 58,
    name: "Cup Case Kukus Polos 9.5",
    unit: "pack",
    price: 35000,
  },
  {
    id: 59,
    name: "Custard Bubuk",
    unit: "klng",
    price: 40000,
  },
  {
    id: 60,
    name: "Dark Soya Sauce",
    unit: "lt",
    price: 42000,
  },
  {
    id: 61,
    name: "Daun Mint",
    unit: "kg",
    price: 50000,
  },
  {
    id: 62,
    name: "Daun Pisang",
    unit: "iket",
    price: 13000,
  },
  {
    id: 63,
    name: "Del Monte Cream Corn",
    unit: "kaleng",
    price: 27000,
  },
  {
    id: 64,
    name: "Dragon Black",
    unit: "pack",
    price: 8000,
  },
  {
    id: 65,
    name: "Elmer Choco Chip 100gr",
    unit: "bks",
    price: 11000,
  },
  {
    id: 66,
    name: "Emping Besar",
    unit: "kg",
    price: 120000,
  },
  {
    id: 67,
    name: "Garam",
    unit: "bks",
    price: 5000,
  },
  {
    id: 68,
    name: "Garam Cap 55",
    unit: "pack",
    price: 7000,
  },
  {
    id: 69,
    name: "Garam Kasar",
    unit: "pack",
    price: 8000,
  },
  {
    id: 70,
    name: "Garam Refina",
    unit: "kg",
    price: 20000,
  },
  {
    id: 71,
    name: "Garam Refina - bks",
    unit: "bks",
    price: 7000,
  },
  {
    id: 72,
    name: "Garam Segitiga Mas",
    unit: "kg",
    price: 20000,
  },
  {
    id: 73,
    name: "Garpu Plastik",
    unit: "bks",
    price: 7000,
  },
  {
    id: 74,
    name: "Gelas Plastik (12Oz)",
    unit: "bks",
    price: 13000,
  },
  {
    id: 75,
    name: "Gula Aren",
    unit: "kg",
    price: 40000,
  },
  {
    id: 76,
    name: "Gula Aren Palm Sugar Cap Pido",
    unit: "pack",
    price: 20000,
  },
  {
    id: 77,
    name: "Gula Bubuk Merk Claris",
    unit: "kg",
    price: 32000,
  },
  {
    id: 78,
    name: "Gula Curah",
    unit: "kg",
    price: 20000,
  },
  {
    id: 79,
    name: "Gula Halus",
    unit: "kg",
    price: 32000,
  },
  {
    id: 80,
    name: "Gula Halus - pack",
    unit: "pack",
    price: 8000,
  },
  {
    id: 81,
    name: "Gula Jawa Hitam",
    unit: "kg",
    price: 23000,
  },
  {
    id: 82,
    name: "Gula Merah",
    unit: "kg",
    price: 23000,
  },
  {
    id: 83,
    name: "Gula Merah Hitam",
    unit: "kg",
    price: 28000,
  },
  {
    id: 84,
    name: "Gula Pasir",
    unit: "kg",
    price: 20000,
  },
  {
    id: 85,
    name: "Gula Sachet",
    unit: "pack",
    price: 11000,
  },
  {
    id: 86,
    name: "Gulaku",
    unit: "kg",
    price: 20000,
  },
  {
    id: 87,
    name: "Gulaku Rosebrand",
    unit: "kg",
    price: 20000,
  },
  {
    id: 88,
    name: "Hakiki Gelatin 100gr",
    unit: "bks",
    price: 43000,
  },
  {
    id: 89,
    name: "Icing Sugar 425gr",
    unit: "pcs",
    price: 26000,
  },
  {
    id: 90,
    name: "Jelly Jeruk Nutrijel",
    unit: "sachet",
    price: 6000,
  },
  {
    id: 91,
    name: "Kacang Kenari",
    unit: "pack",
    price: 44000,
  },
  {
    id: 92,
    name: "Kacang Kenari - kg",
    unit: "kg",
    price: 180000,
  },
  {
    id: 93,
    name: "Kacang Mete",
    unit: "kg",
    price: 140000,
  },
  {
    id: 94,
    name: "Kacang Tanah",
    unit: "kg",
    price: 28000,
  },
  {
    id: 95,
    name: "Kain Pel",
    unit: "pcs",
    price: 30000,
  },
  {
    id: 96,
    name: "Kaldu Ayam Royco",
    unit: "kg",
    price: 50000,
  },
  {
    id: 97,
    name: "Kaldu Ayam Sasa",
    unit: "bks",
    price: 35000,
  },
  {
    id: 98,
    name: "Kaldu Jamur",
    unit: "bks",
    price: 15000,
  },
  {
    id: 99,
    name: "Kaldu Jamur Besar",
    unit: "kg",
    price: 110000,
  },
  {
    id: 100,
    name: "Kaldu Sasa Ayam",
    unit: "kg",
    price: 36000,
  },
  {
    id: 101,
    name: "Karbol",
    unit: "pouch",
    price: 24000,
  },
  {
    id: 102,
    name: "Kecap Asin ABC",
    unit: "btl",
    price: 20000,
  },
  {
    id: 103,
    name: "Kecap Ikan",
    unit: "btl",
    price: 43000,
  },
  {
    id: 104,
    name: "Kecap Inggris",
    unit: "btl",
    price: 40000,
  },
  {
    id: 105,
    name: "Kecap Manis",
    unit: "btl",
    price: 20000,
  },
  {
    id: 106,
    name: "Kecap Manis Bango",
    unit: "pouch",
    price: 26000,
  },
  {
    id: 107,
    name: "Kecap Manis Bango 520ml",
    unit: "pouch",
    price: 26000,
  },
  {
    id: 108,
    name: "Keju Craft",
    unit: "kg",
    price: 105000,
  },
  {
    id: 109,
    name: "Keju Prochiz Gold",
    unit: "kg",
    price: 60000,
  },
  {
    id: 110,
    name: "Kerupuk Mie Kuning",
    unit: "kg",
    price: 34000,
  },
  {
    id: 111,
    name: "Kerupuk Udang",
    unit: "kg",
    price: 45000,
  },
  {
    id: 112,
    name: "Kerupuk Udang Padi Kapas",
    unit: "kg",
    price: 75000,
  },
  {
    id: 113,
    name: "Kismis",
    unit: "kg",
    price: 80000,
  },
  {
    id: 114,
    name: "Kopi Kapal Api 380gr",
    unit: "pack",
    price: 54000,
  },
  {
    id: 115,
    name: "Kopi Tanpa Gula",
    unit: "kg",
    price: 157000,
  },
  {
    id: 116,
    name: "Kulit Spring Roll",
    unit: "pack",
    price: 33000,
  },
  {
    id: 117,
    name: "Kulit Tahu",
    unit: "pack",
    price: 8000,
  },
  {
    id: 118,
    name: "Kupu-Kupu Pasta Strawberry 60ml",
    unit: "btl",
    price: 12000,
  },
  {
    id: 119,
    name: "Kupu-Kupu Pewarna Merah Tua",
    unit: "pcs",
    price: 9000,
  },
  {
    id: 120,
    name: "Kupu-Kupu SP 30gr",
    unit: "bks",
    price: 13000,
  },
  {
    id: 121,
    name: "Lada Hitam Bubuk",
    unit: "btl",
    price: 28000,
  },
  {
    id: 122,
    name: "Lada Putih Bubuk",
    unit: "btl",
    price: 8000,
  },
  {
    id: 123,
    name: "Kulit Putih Halus",
    unit: "kg",
    price: 33000,
  },
  {
    id: 124,
    name: "Lecy Pronas",
    unit: "kaleng",
    price: 47000,
  },
  {
    id: 125,
    name: "Lepatta Fruglaze",
    unit: "bks",
    price: 20000,
  },
  {
    id: 126,
    name: "Lontong",
    unit: "pcs",
    price: 3000,
  },
  {
    id: 127,
    name: "Madu TJ 500ml",
    unit: "btl",
    price: 75000,
  },
  {
    id: 128,
    name: "Madu UK 500ml",
    unit: "btl",
    price: 65000,
  },
  {
    id: 129,
    name: "Madu UK Kecil",
    unit: "botol",
    price: 26000,
  },
  {
    id: 130,
    name: "Maizena Curah",
    unit: "kg",
    price: 20000,
  },
  {
    id: 131,
    name: "Mama Lemon",
    unit: "pouch",
    price: 14000,
  },
  {
    id: 132,
    name: "Mamayo",
    unit: "kg",
    price: 26000,
  },
  {
    id: 133,
    name: "Mamayo Kuning",
    unit: "kg",
    price: 30000,
  },
  {
    id: 134,
    name: "Margarin",
    unit: "kg",
    price: 28000,
  },
  {
    id: 135,
    name: "Masako Ayam",
    unit: "kg",
    price: 45000,
  },
  {
    id: 136,
    name: "Masako Daging",
    unit: "kg",
    price: 45000,
  },
  {
    id: 137,
    name: "Masako Sapi",
    unit: "kg",
    price: 40000,
  },
  {
    id: 138,
    name: "Mayonaise Mamayo",
    unit: "kg",
    price: 30000,
  },
  {
    id: 139,
    name: "Mecin",
    unit: "pack",
    price: 3000,
  },
  {
    id: 140,
    name: "Mecin Miwon",
    unit: "kg",
    price: 55000,
  },
  {
    id: 141,
    name: "Micin",
    unit: "bks",
    price: 12000,
  },
  {
    id: 142,
    name: "Micin Sasa",
    unit: "kg",
    price: 60000,
  },
  {
    id: 143,
    name: "Mie Atom Bulan",
    unit: "pack",
    price: 8000,
  },
  {
    id: 144,
    name: "Mie Hongkong",
    unit: "kg",
    price: 40000,
  },
  {
    id: 145,
    name: "Mie Kuning",
    unit: "pcs",
    price: 7000,
  },
  {
    id: 146,
    name: "Mie Kuning Pasar",
    unit: "kg",
    price: 15000,
  },
  {
    id: 147,
    name: "Mie Telur",
    unit: "pcs",
    price: 7000,
  },
  {
    id: 148,
    name: "Minyak",
    unit: "lt",
    price: 18000,
  },
  {
    id: 149,
    name: "Minyak - drg",
    unit: "drg",
    price: 90000,
  },
  {
    id: 150,
    name: "Minyak Bimoli",
    unit: "lt",
    price: 21000,
  },
  {
    id: 151,
    name: "Minyak Curah",
    unit: "lt",
    price: 18000,
  },
  {
    id: 152,
    name: "Minyak Fitri",
    unit: "lt",
    price: 21000,
  },
  {
    id: 153,
    name: "Minyak Goreng",
    unit: "lt",
    price: 21000,
  },
  {
    id: 154,
    name: "Minyak Goreng - dus",
    unit: "dus",
    price: 240000,
  },
  {
    id: 155,
    name: "Minyak Goreng Bimoli 2lt",
    unit: "lt",
    price: 42000,
  },
  {
    id: 156,
    name: "Minyak Goreng Fitri",
    unit: "lt",
    price: 22000,
  },
  {
    id: 157,
    name: "Minyak Ikan (uk besar)",
    unit: "btl",
    price: 43000,
  },
  {
    id: 158,
    name: "Minyak Ikan (uk kecil)",
    unit: "btl",
    price: 15000,
  },
  {
    id: 159,
    name: "Minyak Kita",
    unit: "lt",
    price: 20000,
  },
  {
    id: 160,
    name: "Minyak Sayur",
    unit: "lt",
    price: 21000,
  },
  {
    id: 161,
    name: "Minyak Sayur Kita",
    unit: "lt",
    price: 19000,
  },
  {
    id: 162,
    name: "Minyak Wijen",
    unit: "btl",
    price: 43000,
  },
  {
    id: 163,
    name: "Minyak Wijen uk 600ml",
    unit: "btl",
    price: 43000,
  },
  {
    id: 164,
    name: "Miwon",
    unit: "kg",
    price: 60000,
  },
  {
    id: 165,
    name: "Nutjel Coklat",
    unit: "box",
    price: 70000,
  },
  {
    id: 166,
    name: "Nutjel Mangga",
    unit: "box",
    price: 58000,
  },
  {
    id: 167,
    name: "Nutjel Plain",
    unit: "box",
    price: 60000,
  },
  {
    id: 168,
    name: "Orange Juice",
    unit: "lt",
    price: 45000,
  },
  {
    id: 169,
    name: "Orange Juice Jungle",
    unit: "lt",
    price: 35000,
  },
  {
    id: 170,
    name: "Origano",
    unit: "btl",
    price: 32000,
  },
  {
    id: 171,
    name: "Origano 250gr",
    unit: "kg",
    price: 45000,
  },
  {
    id: 172,
    name: "Ovalet",
    unit: "pack",
    price: 17000,
  },
  {
    id: 173,
    name: "Paper Cup dan Tutup",
    unit: "bks",
    price: 25000,
  },
  {
    id: 174,
    name: "Paprika Bubuk",
    unit: "btl",
    price: 35000,
  },
  {
    id: 175,
    name: "Pastry Cup Case",
    unit: "pack",
    price: 27000,
  },
  {
    id: 176,
    name: "Perasa Lemon",
    unit: "btl",
    price: 32000,
  },
  {
    id: 177,
    name: "Perasa Matcha",
    unit: "btl",
    price: 30000,
  },
  {
    id: 178,
    name: "Perasa Vanilla",
    unit: "btl",
    price: 12000,
  },
  {
    id: 179,
    name: "Perasa Vanilla Susu",
    unit: "btl",
    price: 30000,
  },
  {
    id: 180,
    name: "Pewarna Hijau Pandan",
    unit: "btl",
    price: 10000,
  },
  {
    id: 181,
    name: "Pewarna Kuning",
    unit: "btl",
    price: 7000,
  },
  {
    id: 182,
    name: "Piping Bag",
    unit: "pack",
    price: 30000,
  },
  {
    id: 183,
    name: "Plastik ATP Uk 10x20",
    unit: "bks",
    price: 12000,
  },
  {
    id: 184,
    name: "Plastik ATP Uk 12x25",
    unit: "bks",
    price: 14000,
  },
  {
    id: 185,
    name: "Plastik ATP Uk 15x30",
    unit: "bks",
    price: 15000,
  },
  {
    id: 186,
    name: "Plastik Klip Uk 10x16",
    unit: "bks",
    price: 7000,
  },
  {
    id: 187,
    name: "Plastik Klip Uk 10x7",
    unit: "pcs",
    price: 7000,
  },
  {
    id: 188,
    name: "Plastik Loco Uk 17",
    unit: "pcs",
    price: 17000,
  },
  {
    id: 189,
    name: "Plastik Loco Uk 24",
    unit: "pcs",
    price: 17000,
  },
  {
    id: 190,
    name: "Plastik Loco Uk 28",
    unit: "bks",
    price: 17000,
  },
  {
    id: 191,
    name: "Plastik Sampah",
    unit: "bks",
    price: 14000,
  },
  {
    id: 192,
    name: "Plastik Sampah (60x100)",
    unit: "bks",
    price: 14000,
  },
  {
    id: 193,
    name: "Plastik Sampah (90x120)",
    unit: "bks",
    price: 15000,
  },
  {
    id: 194,
    name: "Plastik Tomat 1/2 kg",
    unit: "bks",
    price: 17000,
  },
  {
    id: 195,
    name: "Plastik Tomat Uk 15x30",
    unit: "bks",
    price: 10000,
  },
  {
    id: 196,
    name: "Plastik Wrapping",
    unit: "bks",
    price: 18000,
  },
  {
    id: 197,
    name: "Puff Pastry",
    unit: "pack",
    price: 50000,
  },
  {
    id: 198,
    name: "Rap Zeelandia",
    unit: "kg",
    price: 110000,
  },
  {
    id: 199,
    name: "Rap Zeelandia 250gr",
    unit: "bks",
    price: 27000,
  },
  {
    id: 200,
    name: "Rice Noodle",
    unit: "pack",
    price: 50000,
  },
  {
    id: 201,
    name: "Rich Cream",
    unit: "lt",
    price: 62000,
  },
  {
    id: 202,
    name: "Rich Gold Label",
    unit: "pcs",
    price: 62000,
  },
  {
    id: 203,
    name: "Roti Tawar",
    unit: "pack",
    price: 18000,
  },
  {
    id: 204,
    name: "Roti Tawar Biasa",
    unit: "pack",
    price: 15000,
  },
  {
    id: 205,
    name: "Santan Kara",
    unit: "lt",
    price: 35000,
  },
  {
    id: 206,
    name: "Santan Kara 2lt",
    unit: "lt",
    price: 35000,
  },
  {
    id: 207,
    name: "Saori Saos Tiram",
    unit: "lt",
    price: 60000,
  },
  {
    id: 208,
    name: "Saos Bbq Del Monte 1kg",
    unit: "kg",
    price: 40000,
  },
  {
    id: 209,
    name: "Saos Bbq My Taste 500gr",
    unit: "kg",
    price: 20000,
  },
  {
    id: 210,
    name: "Saos Del Monte",
    unit: "kg",
    price: 30000,
  },
  {
    id: 211,
    name: "Saos Tiram",
    unit: "btl",
    price: 60000,
  },
  {
    id: 212,
    name: "Sasa Kaldu Sapi",
    unit: "kg",
    price: 40000,
  },
  {
    id: 213,
    name: "Sasa Penyedap",
    unit: "kg",
    price: 15000,
  },
  {
    id: 214,
    name: "Saus Sachet ABC",
    unit: "pack",
    price: 10000,
  },
  {
    id: 215,
    name: "Saus Sambal ABC",
    unit: "pack",
    price: 10000,
  },
  {
    id: 216,
    name: "Saus Sambal ABC 1kg",
    unit: "pack",
    price: 30000,
  },
  {
    id: 217,
    name: "Saus Sambal ABC 5kg",
    unit: "drigen",
    price: 175000,
  },
  {
    id: 218,
    name: "Saus Sambal Belibis",
    unit: "pouch",
    price: 38000,
  },
  {
    id: 219,
    name: "Saus Tomat ABC",
    unit: "kg",
    price: 30000,
  },
  {
    id: 220,
    name: "Saus Tomat ABC 1kg",
    unit: "pouch",
    price: 30000,
  },
  {
    id: 221,
    name: "SC Tiram UK 510ml Cap Panda",
    unit: "btl",
    price: 56000,
  },
  {
    id: 222,
    name: "SC Tiram UK 600ml",
    unit: "btl",
    price: 63000,
  },
  {
    id: 223,
    name: "Sedotan Steril",
    unit: "bks",
    price: 15000,
  },
  {
    id: 224,
    name: "Sedotan Steril (kemasan kecil)",
    unit: "bks",
    price: 7000,
  },
  {
    id: 225,
    name: "Selai Coklat Merk Tulip",
    unit: "kg",
    price: 120000,
  },
  {
    id: 226,
    name: "Selai Nastar",
    unit: "kg",
    price: 90000,
  },
  {
    id: 227,
    name: "Selai Strawberry",
    unit: "kg",
    price: 27000,
  },
  {
    id: 228,
    name: "Sendok Plastik",
    unit: "bks",
    price: 7000,
  },
  {
    id: 229,
    name: "Shine Road Topping 1kg",
    unit: "pcs",
    price: 60000,
  },
  {
    id: 230,
    name: "Silica Gel",
    unit: "pcs",
    price: 500,
  },
  {
    id: 231,
    name: "Silica Gel - Pack",
    unit: "pack",
    price: 25000,
  },
  {
    id: 232,
    name: "Simas",
    unit: "kg",
    price: 28000,
  },
  {
    id: 233,
    name: "Simas - dus",
    unit: "dus",
    price: 350000,
  },
  {
    id: 234,
    name: "Simas Margarin",
    unit: "dus",
    price: 345000,
  },
  {
    id: 235,
    name: "SKM Cap Enak",
    unit: "klg",
    price: 14000,
  },
  {
    id: 236,
    name: "SKM Cap Enak - dus",
    unit: "dus",
    price: 560000,
  },
  {
    id: 237,
    name: "SKM Coklat",
    unit: "klg",
    price: 14000,
  },
  {
    id: 238,
    name: "Soda Api",
    unit: "pcs",
    price: 25000,
  },
  {
    id: 239,
    name: "Soklin",
    unit: "pouch",
    price: 15500,
  },
  {
    id: 240,
    name: "Soklin Lantai",
    unit: "pouch",
    price: 15500,
  },
  {
    id: 241,
    name: "Soun Cap Naga",
    unit: "pack",
    price: 12000,
  },
  {
    id: 242,
    name: "Spons Busa",
    unit: "pcs",
    price: 4000,
  },
  {
    id: 243,
    name: "Spons Kawat",
    unit: "pcs",
    price: 5000,
  },
  {
    id: 244,
    name: "Strawberry Jam",
    unit: "kg",
    price: 57000,
  },
  {
    id: 245,
    name: "Sunlight",
    unit: "pouch",
    price: 14000,
  },
  {
    id: 246,
    name: "Sunlight 420ml",
    unit: "pouch",
    price: 12000,
  },
  {
    id: 247,
    name: "Sunlight 635ml",
    unit: "pouch",
    price: 14000,
  },
  {
    id: 248,
    name: "Sunlight 650ml",
    unit: "pouch",
    price: 14000,
  },
  {
    id: 249,
    name: "Sunlight 700ml",
    unit: "pouch",
    price: 16000,
  },
  {
    id: 250,
    name: "Sunquick Orange",
    unit: "btl",
    price: 45000,
  },
  {
    id: 251,
    name: "Susu Full Cream UHT Diamond",
    unit: "ml",
    price: 23000,
  },
  {
    id: 252,
    name: "Susu UHT Ultra Milk",
    unit: "btl",
    price: 22000,
  },
  {
    id: 253,
    name: "Syrup Bango",
    unit: "btl",
    price: 25000,
  },
  {
    id: 254,
    name: "Syrup Lecy",
    unit: "btl",
    price: 20000,
  },
  {
    id: 255,
    name: "Syrup Marjan Straw",
    unit: "btl",
    price: 28000,
  },
  {
    id: 256,
    name: "Tahu Cina",
    unit: "kotak",
    price: 7000,
  },
  {
    id: 257,
    name: "Tahu Jepang Kong Kee",
    unit: "pcs",
    price: 7000,
  },
  {
    id: 258,
    name: "Tahu Kuning",
    unit: "pcs",
    price: 1500,
  },
  {
    id: 259,
    name: "Teh Perendjak",
    unit: "pack",
    price: 13000,
  },
  {
    id: 260,
    name: "Telur Asin",
    unit: "pcs",
    price: 5000,
  },
  {
    id: 261,
    name: "Telur Ayam",
    unit: "kg",
    price: 30000,
  },
  {
    id: 262,
    name: "Telur Puyuh",
    unit: "pcs",
    price: 1500,
  },
  {
    id: 263,
    name: "Tempe",
    unit: "papan",
    price: 8000,
  },
  {
    id: 264,
    name: "Tempe Iris",
    unit: "papan",
    price: 10000,
  },
  {
    id: 265,
    name: "Tempe Mendoan",
    unit: "pcs",
    price: 3000,
  },
  {
    id: 266,
    name: "Tepung Beras",
    unit: "kg",
    price: 20000,
  },
  {
    id: 267,
    name: "Tepung Maizena",
    unit: "kg",
    price: 20000,
  },
  {
    id: 268,
    name: "Tepung Maizena - pack",
    unit: "pack",
    price: 12000,
  },
  {
    id: 269,
    name: "Tepung Roti",
    unit: "bal",
    price: 190000,
  },
  {
    id: 270,
    name: "Tepung Roti Panko",
    unit: "bal",
    price: 190000,
  },
  {
    id: 271,
    name: "Tepung Roti Primerah",
    unit: "kg",
    price: 21000,
  },
  {
    id: 272,
    name: "Tepung Sasa Sapi",
    unit: "kg",
    price: 37000,
  },
  {
    id: 273,
    name: "Terasi Samhok",
    unit: "pcs",
    price: 10000,
  },
  {
    id: 274,
    name: "Terasi Udang",
    unit: "pack",
    price: 10000,
  },
  {
    id: 275,
    name: "Terigu Cakra",
    unit: "kg",
    price: 15000,
  },
  {
    id: 276,
    name: "Terigu Kunci Biru",
    unit: "kg",
    price: 14000,
  },
  {
    id: 277,
    name: "Terigu Lencana Merah",
    unit: "krg",
    price: 225000,
  },
  {
    id: 278,
    name: "Terigu Segitiga Biru",
    unit: "kg",
    price: 14000,
  },
  {
    id: 279,
    name: "Thin Wall Bulat 400ml",
    unit: "pack",
    price: 20000,
  },
  {
    id: 280,
    name: "Thyme Jay's",
    unit: "btl",
    price: 31000,
  },
  {
    id: 281,
    name: "Tofu Udang",
    unit: "pcs",
    price: 7500,
  },
  {
    id: 282,
    name: "Tong Jie",
    unit: "pack",
    price: 8000,
  },
  {
    id: 283,
    name: "Tong Jie Melati isi 10",
    unit: "pack",
    price: 15000,
  },
  {
    id: 284,
    name: "Toping Coklat",
    unit: "kg",
    price: 36000,
  },
  {
    id: 285,
    name: "Toping Strawberry",
    unit: "klg",
    price: 30000,
  },
  {
    id: 286,
    name: "Tortilla",
    unit: "pack",
    price: 27000,
  },
  {
    id: 287,
    name: "Tropicana Slim",
    unit: "pack",
    price: 1500,
  },
  {
    id: 288,
    name: "Tropicana Slim isi 80pcs",
    unit: "pack",
    price: 70000,
  },
  {
    id: 289,
    name: "Tulip Filling Dark 500gr",
    unit: "bks",
    price: 32000,
  },
  {
    id: 290,
    name: "Tusuk Sate Panda",
    unit: "pack",
    price: 15000,
  },
  {
    id: 291,
    name: "Vanili Bubuk",
    unit: "btl",
    price: 10000,
  },
  {
    id: 292,
    name: "Vanili Bubuk Merk Kupu-Kupu",
    unit: "btl",
    price: 12000,
  },
  {
    id: 293,
    name: "Vanilla Nutri Jelly",
    unit: "pack",
    price: 30000,
  },
  {
    id: 294,
    name: "White Chocolate",
    unit: "kg",
    price: 23000,
  },
  {
    id: 295,
    name: "Wilmond Mandarin 312gr",
    unit: "klg",
    price: 22000,
  },
  {
    id: 296,
    name: "Wipol",
    unit: "btl",
    price: 24000,
  },
];
